theme: jekyll-theme-architect

title: [JAX-WS]
description: [Java API for XML Web Services]

# sidebar links url
links:
  source: https://github.com/javaee/metro-jax-ws
  #download: download
  mailinglist: https://javaee.groups.io/g/metro
  #javadocs:
  userguide: doc/user-guide/index.html
  
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

